import { Modal } from './Modal'

type LoginRequiredModalProps = {
  isOpen: boolean
  onClose: () => void
  onLoginClick: () => void
}

export function LoginRequiredModal({ isOpen, onClose, onLoginClick }: LoginRequiredModalProps) {
  return (
    <Modal isOpen={isOpen} onClose={onClose} title="New Discovery Awaits!">
      <div class="space-y-4">
        <p class="text-gray-700">
          The combination you've just tried is something nobody has attempted before! 
          Exciting new discoveries await.
        </p>
        <p class="text-gray-700">
          To prevent abuse, we only allow new elements to be generated by users who are signed in.
        </p>
        <button
          onClick={onLoginClick}
          class="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-colors"
        >
          Sign in with Email
        </button>
        <p class="text-sm text-gray-500 text-center">
          We only use your email to send the login link.
        </p>
      </div>
    </Modal>
  )
}
